updated Readme
ijemmao/igbo-api-admin pull request #8
Opened 2021-11-22 19:36 UTC by Ebugo

2021-11-24 02:57 UTC, ijemmao commented on README.md
> +If an error is thrown, build the project by running:
Can you be more specific about which error you're referencing? Or maybe it might be more helpful to have a new Troubleshooting section of the README that could be referenced?

2021-11-24 14:50 UTC, Ebugo commented on README.md
> +If an error is thrown, build the project by running:
okay, fixing this now

2021-11-25 06:16 UTC, Ebugo commented
I've just added a contributing.md file @ijemmao, please do check it out and let me know what you think.

2021-11-26 17:19 UTC, ijemmao commented on README.md
> +If you encounter this error - ```Error: Cannot find module '/root-path/igbo-api-admin/functions/index.js'. Please verify that the package.json has a valid "main" entry``` - build the project by runni
Can you link to the new contributing guide at the top of the README?

2021-11-26 17:20 UTC, ijemmao commented on CONTRIBUTING.md
> +3. You may merge the Pull Request in once you have the sign-off of two other developers, or if you
Sign off from the project owner @ijemmao

2021-11-26 17:21 UTC, ijemmao commented on CONTRIBUTING.md
> +2. Update the README.md with details of changes to the interface, this includes new environment
You will need to mention that their own repo will need to be forked

Igbo API CONTRIBUTING.md: https://github.com/ijemmao/igbo_api/blob/master/.github/CONTRIBUTING.md

2021-11-26 17:21 UTC, ijemmao requested changes
let's closely follow the Igbo API Contributing guide

2021-11-29 17:40 UTC, Ebugo commented on README.md
> +If you encounter this error - ```Error: Cannot find module '/root-path/igbo-api-admin/functions/index.js'. Please verify that the package.json has a valid "main" entry``` - build the project by runni
Okay, doing this right away

2022-01-05 05:09 UTC, merged